<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>Major</RollForward>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <SonarrDir Condition="'$(SonarrDir)' == ''">/workspaces/Sonarr/_output/net6.0/linux-x64/publish</SonarrDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\SonarrPatcher.Common\**\*.cs" LinkBase="Common" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.4.13" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SonarrPatcher.Loader\SonarrPatcher.Loader.csproj" />
    <ProjectReference Include="..\SonarrPatcher.Patches\SkyHook\SonarrPatcher.Patches.SkyHook.csproj" />
    <ProjectReference Include="..\SonarrPatcher.Patches\NameTruncate\SonarrPatcher.Patches.NameTruncate.csproj" />
    <ProjectReference Include="..\SonarrPatcher.Patches\XemAliases\SonarrPatcher.Patches.XemAliases.csproj" />
    <ProjectReference Include="..\SonarrPatcher.Patches\CustomParseRules\SonarrPatcher.Patches.CustomParseRules.csproj" />
    <ProjectReference Include="..\SonarrPatcher.TestTarget\SonarrPatcher.TestTarget.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup Condition="Exists('$(SonarrDir)\Sonarr.Common.dll') and Exists('$(SonarrDir)\0Harmony.dll')">
    <None Include="$(SonarrDir)\Sonarr.Common.dll" Link="Sonarr.Common.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(SonarrDir)\0Harmony.dll" Link="0Harmony.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(SonarrDir)\Sonarr.Core.dll" Link="Sonarr.Core.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(SonarrDir)\NLog.dll" Link="NLog.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(SonarrDir)\NLog.Layouts.ClefJsonLayout.dll" Link="NLog.Layouts.ClefJsonLayout.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Include="custom-parse-rules.example.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="CopyTestTargetDll" AfterTargets="Build">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\SonarrPatcher.TestTarget\bin\$(Configuration)\net6.0\SonarrPatcher.TestTarget.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
