<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>SonarrPatcher.TestTarget</AssemblyName>
    <RootNamespace>SonarrPatcher.TestTarget</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
</Project>
